Netliva\OptionsBundle\Entity\Options:
    type: entity
    table: NetlivaOptions
    id:
        id:
            column: NO_AutoID
            type: integer
            generator: { strategy: AUTO }
    fields:
        keyword:
            column: NO_Key
            type: string
            length: 255
        value:
            column: NO_Value
            type: json_array
            nullable: true
